# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DTST1', null=True, verbose_name='DTSM1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DTST2', null=True, verbose_name='DTSM2')),
                ('name', models.CharField(help_text='name', max_length=200, verbose_name='name')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DTST1', null=True, verbose_name='DTSM1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DTST2', null=True, verbose_name='DTSM2')),
                ('name', models.CharField(help_text='name', max_length=200, verbose_name='name')),
                ('supervisor_name', models.CharField(max_length=200)),
                ('supervisor_mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('supervisor_home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('supervisor_email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DTST1', null=True, verbose_name='DTSM1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DTST2', null=True, verbose_name='DTSM2')),
                ('code', models.CharField(max_length=200)),
                ('catalog_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DTST1', null=True, verbose_name='DTSM1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DTST2', null=True, verbose_name='DTSM2')),
                ('campaign', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_company', to='api.Company')),
                ('items', models.ManyToManyField(related_name='order_itens', to='api.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='DTST1', null=True, verbose_name='DTSM1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='DTST2', null=True, verbose_name='DTSM2')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='api.Status'),
        ),
    ]
